### ISSUE TITLE
Slow calls to the asd-manager

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/alba-asdmanager#272] opened 2017-08-21 09:35 UTC
### Problem description
Investigating the backend page load times has led me to the asd-manager. Fetching the local stack could take quite a while.
https://github.com/openvstorage/framework-alba-plugin/issues/439

Restarting the asd-manager had temporarily fixed the issue.

The root cause is most likely the VM swapping.

**Comment by wimpers** [comment] 2017-08-23 13:55
@JeffreyDevloo so the asd manager is taking too much mem? Hence the fix of @domsj will not fix this one?

**Comment by JeffreyDevloo** [comment] 2018-01-09 15:50
@wimpers 
The asd-manager its memory consumption was hardly anything

Operations saw something where processes their memory would be swapped even when there is enough memory available for use
Could be something similar to that...

**Comment by wimpers** [comment] 2018-08-20 07:58
@JeffreyDevloo  is it relevant to leave this open. Memory not being available is probably caused by
* alba components
* the fact this runs in a VM

I suggest to close this one down. Ok?

**Comment by wimpers** [comment] 2018-09-03 09:45
The assumption is that this isn't caused by the ASD manager but due to above facts. hence closing this one down. Re-open if we have evidence.

**Closed by wimpers** 2018-09-03 09:45 UTC
