### ISSUE TITLE
asd-manager uninstall

### ISSUE THREAD

**Issue by simonOpenV** [openvstorage/alba-asdmanager#317] opened 2018-02-13 14:49 UTC
## Issue
Right now, the ASD-manager uninstall proceeds as follows: 
- In the GUI, the ASD node is removed
- ` asd-manager remove` command is ran in the command line.

## Fix
I propose to make the asd-manager removal independent of the GUI: 
- No need to first clear the ASD-node through the GUI
- Automatically inform alba of recent changes

**Comment by wimpers** [comment] 2018-02-22 08:40
@simonOpenV 

I don't understand what the issue is exactly. I assume that the removal is now 2 independent procedures (remove from model and remove from the physical node)?

It should be possible to remove the ASD manager & Node in following cases:
* In case the ASD manager is online, remove the ASD node through the GUI which removes it from the model and next removes the asd manager from the physical node (all in 1 go).
* Run asd-manager remove, removes the asd manager from the physical node and (if even possible) remove it from the model. 
* In case the ASD manager is not online (physical node is down), possible to remove it from the model through the GUI.

**Comment by simonOpenV** [comment] 2018-02-22 09:39
`Run asd-manager remove, removes the asd manager from the physical node and (if even possible) remove it from the model.
`
Right now, if you reinstall the asd-manager with initialized but unclaimed OSDs, these OSDs are in warning on the reinstalled node, and they cannot be restarted through the GUI. 
(due to error: 
`Failed removing ASD ztw7TVmYhJDIUIfK2lQpTmO7XjePNe3x: 'NoneType' object has no attribute 'alba_backend'`)
Therefore I propose to make the clear slots function part of the `asd-manager remove`. Or is there any value in these initialized but unclaimed OSDs, @JeffreyDevloo ?

**Comment by JeffreyDevloo** [comment] 2018-02-22 10:27
The Framework does not know of the reinstall in that case. The current 'stack' of the AlbaNode is pointing towards the older one.
I'd propose to document the sequence:
 - Remove ASD manager
 - Install ASD Manager
 - Invalidate stack dynamic for the associated ASD node
 or that we try to invalidate the stack after failing to remove the ASD

**Comment by wimpers** [comment] 2018-06-19 13:53
Closing this one down as there is a documented work-around.

**Closed by wimpers** 2018-06-19 13:53 UTC
Labels: process_wontfix, type_enhancement
