### ISSUE TITLE
python-requests package is missing when installing openvstorage-sdm

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/alba-asdmanager#88] opened 2016-06-16 12:32 UTC
When trying to start the setup of openvstorage-sdm, it does not work because the python-requests package is missing

**Comment by khenderick** [comment] 2016-09-06 09:58
Fixed by #100, available in openvstorage-sdm-1.6.3-rev.346.3c58610, fixed by @kinvaris

**Comment by JeffreyDevloo** [comment] 2016-09-19 13:19
During multiple installs of the OVH environment, we were unable to reproduce this issue.

### Steps
- Ran ovs setup (attended and unattended)
- Installed sdm or storage nodes

### Output
All sdm installs were succesfull.

**Closed by JeffreyDevloo** 2016-09-19 13:19 UTC
Labels: priority_critical, state_verification, type_bug
