### ISSUE TITLE
Pyarakoon receives unknown master during master validation

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/alba-asdmanager#155] opened 2016-11-15 12:30 UTC
Related to:
http://tickets.openvstorage.com/browse/OVSSUP-128
http://tickets.openvstorage.com/browse/OVSSUP-127

I was going to upgrade an environment on gig when I observed the following:
* I could not fetch the updates of a `asd-manager`, I got a `read timeout` error.
* After looking deeper I found the give error in the `asd-manager` log.
* After advice of @khenderick, I restarted the `asd-manager` service an everything was normal again.
```
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]: 2016-11-15 13:24:15 88200 +0100 - stor-06.be-g8-4 - 34905/139837684311808 - arakoon_client/pyrakoon - 628815 - ERROR - Unable to determine master node
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]: 2016-11-15 13:24:15 88200 +0100 - stor-06.be-g8-4 - 34905/139837684311808 - arakoon_client/pyrakoon - 628816 - WARNING - Master not found, retrying in 0.20 seconds
Nov 15 13:24:16 stor-06.be-g8-4 python[34905]: 2016-11-15 13:24:16 08300 +0100 - stor-06.be-g8-4 - 34905/139837684311808 - arakoon_client/pyrakoon - 628817 - ERROR - 'XfSf0oRnZ0yyq2sH' : Message exchange with node XfSf0oRnZ0yyq2sH failed
Nov 15 13:24:16 stor-06.be-g8-4 python[34905]: Traceback (most recent call last):
Nov 15 13:24:16 stor-06.be-g8-4 python[34905]:   File "/opt/asd-manager/source/tools/pyrakoon/pyrakoon/compat.py", line 1137, in _send_message
Nov 15 13:24:16 stor-06.be-g8-4 python[34905]:     connection = self._get_connection(node_id)
Nov 15 13:24:16 stor-06.be-g8-4 python[34905]:   File "/opt/asd-manager/source/tools/pyrakoon/pyrakoon/compat.py", line 1227, in _get_connection
Nov 15 13:24:16 stor-06.be-g8-4 python[34905]:     node_location = self._config.getNodeLocation(node_id)
Nov 15 13:24:16 stor-06.be-g8-4 python[34905]:   File "/opt/asd-manager/source/tools/pyrakoon/pyrakoon/compat.py", line 1014, in getNodeLocation
Nov 15 13:24:16 stor-06.be-g8-4 python[34905]:     ips, port = self.getNodeLocations(nodeId)
Nov 15 13:24:16 stor-06.be-g8-4 python[34905]:   File "/opt/asd-manager/source/tools/pyrakoon/pyrakoon/compat.py", line 999, in getNodeLocations
Nov 15 13:24:16 stor-06.be-g8-4 python[34905]:     return self._nodes[nodeId]
Nov 15 13:24:16 stor-06.be-g8-4 python[34905]: KeyError: 'XfSf0oRnZ0yyq2sH'
Nov 15 13:24:16 stor-06.be-g8-4 python[34905]: 2016-11-15 13:24:16 08400 +0100 - stor-06.be-g8-4 - 34905/139837684311808 - arakoon_client/pyrakoon - 628818 - ERROR - 'XfSf0oRnZ0yyq2sH': Unable to validate master on node XfSf0oRnZ0yyq2sH
Nov 15 13:24:16 stor-06.be-g8-4 python[34905]: Traceback (most recent call last):
Nov 15 13:24:16 stor-06.be-g8-4 python[34905]:   File "/opt/asd-manager/source/tools/pyrakoon/pyrakoon/compat.py", line 1185, in determine_master
Nov 15 13:24:16 stor-06.be-g8-4 python[34905]:     self._validate_master_id(self.master_id):
Nov 15 13:24:16 stor-06.be-g8-4 python[34905]:   File "/opt/asd-manager/source/tools/pyrakoon/pyrakoon/compat.py", line 1216, in _validate_master_id
Nov 15 13:24:16 stor-06.be-g8-4 python[34905]:     other_master_id = self._get_master_id_from_node(master_id)
Nov 15 13:24:16 stor-06.be-g8-4 python[34905]:   File "/opt/asd-manager/source/tools/pyrakoon/pyrakoon/compat.py", line 1207, in _get_master_id_from_node
Nov 15 13:24:16 stor-06.be-g8-4 python[34905]:     connection = self._send_message(node_id, data)
Nov 15 13:24:16 stor-06.be-g8-4 python[34905]:   File "/opt/asd-manager/source/tools/pyrakoon/pyrakoon/compat.py", line 1146, in _send_message
Nov 15 13:24:16 stor-06.be-g8-4 python[34905]:     self._connections.pop(node_id).close()
Nov 15 13:24:16 stor-06.be-g8-4 python[34905]: KeyError: 'XfSf0oRnZ0yyq2sH'
Nov 15 13:24:16 stor-06.be-g8-4 python[34905]: 2016-11-15 13:24:16 08400 +0100 - stor-06.be-g8-4 - 34905/139837684311808 - arakoon_client/pyrakoon - 628819 - ERROR - Unable to determine master node
Nov 15 13:24:16 stor-06.be-g8-4 python[34905]: 2016-11-15 13:24:16 08400 +0100 - stor-06.be-g8-4 - 34905/139837684311808 - arakoon_client/pyrakoon - 628820 - WARNING - Master not found, retrying in 0.40 seconds
Nov 15 13:24:16 stor-06.be-g8-4 python[34905]: 2016-11-15 13:24:16 48500 +0100 - stor-06.be-g8-4 - 34905/139837684311808 - arakoon_client/pyrakoon - 628821 - ERROR - 'XfSf0oRnZ0yyq2sH' : Message exchange with node XfSf0oRnZ0yyq2sH failed
```

```
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]: 2016-11-15 13:24:15 87600 +0100 - stor-06.be-g8-4 - 34905/139844126762752 - asd-manager/source.app - 628807 - ERROR - Exception on /disks [GET]
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]: Traceback (most recent call last):
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:     response = self.full_dispatch_request()
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:     rv = self.handle_user_exception(e)
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:     reraise(exc_type, exc_value, tb)
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:     rv = self.dispatch_request()
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:   File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:     return self.view_functions[rule.endpoint](**req.view_args)
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:   File "/opt/asd-manager/source/app/decorators.py", line 68, in new_function
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:     if authenticate is True and not _authorized():
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:   File "/opt/asd-manager/source/app/decorators.py", line 108, in _authorized
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:     username = Configuration.get('/ovs/alba/asdnodes/{0}/config/main|username'.format(NODE_ID))
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:   File "/opt/asd-manager/source/tools/configuration/configuration.py", line 95, in get
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:     data = Configuration._get(key_entries[0], raw)
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:   File "/opt/asd-manager/source/tools/configuration/configuration.py", line 307, in _get
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:     key=key)
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:   File "/opt/asd-manager/source/tools/configuration/configuration.py", line 349, in _passthrough
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:     return getattr(ArakoonConfiguration, method)(*args, **kwargs)
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:   File "/opt/asd-manager/source/tools/configuration/arakoon_config.py", line 119, in get
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:     return client.get(key)
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:   File "/opt/asd-manager/source/tools/pyrakoon/client.py", line 44, in new_function
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:     return f(self, *args, **kw)
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:   File "/opt/asd-manager/source/tools/pyrakoon/client.py", line 76, in get
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:     return PyrakoonClient._try(self._identifier, self._client.get, key, consistency)
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:   File "/opt/asd-manager/source/tools/pyrakoon/client.py", line 207, in _try
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:     return_value = method(*args, **kwargs)
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:   File "<update_argspec>", line 5, in get
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:   File "/opt/asd-manager/source/tools/pyrakoon/pyrakoon/compat.py", line 145, in wrapped
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:     return fun(*args, **kwargs)
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:   File "/opt/asd-manager/source/tools/pyrakoon/pyrakoon/compat.py", line 128, in wrapped
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:     return fun(*new_args)
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:   File "/opt/asd-manager/source/tools/pyrakoon/pyrakoon/compat.py", line 246, in get
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:     return self._client.get(key,consistency = consistency_)
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:   File "<update_argspec>", line 5, in get
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:   File "/opt/asd-manager/source/tools/pyrakoon/pyrakoon/client/utils.py", line 99, in wrapped
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:     return self._process(message) #pylint: disable=W0212
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:   File "/opt/asd-manager/source/tools/pyrakoon/pyrakoon/compat.py", line 1099, in _process
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:     connection = self._send_to_master(bytes_)
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:   File "/opt/asd-manager/source/tools/pyrakoon/pyrakoon/compat.py", line 1158, in _send_to_master
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:     self.determine_master()
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:   File "/opt/asd-manager/source/tools/pyrakoon/pyrakoon/compat.py", line 1201, in determine_master
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]:     raise ArakoonNoMaster
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]: ArakoonNoMaster: Could not determine the Arakoon master node
Nov 15 13:24:15 stor-06.be-g8-4 python[34905]: 2016-11-15 13:24:15 87800 +0100 - stor-06.be-g8-4 - 34905/139844126762752 - asd-manager/werkzeug - 628808 - INFO - 10.109.1.46 - - [15/Nov/2016 13:24:15] "GET /disks HTTP/1.1" 500
```

**Comment by khenderick** [comment] 2016-12-05 14:26
So far the expected cause seems to be validated. To reproduce, setup a single node ovs and make sure to create a backend with some asds on it. Then extend the cluster to a 3 node setup. No need to do anything with the backend.

After the third node is present, you might notice that the asd-manager service did not restart, so it's runtime only knows about a single node arakoon while it has been extended to 3 nodes in the meantime. Stopping the config arakoon on the first node, will cause the reported issue, since the asdmanager's runtime doesn't know of the other nodes. 

Restarting the asd-manager will make everything run again.

**Comment by khenderick** [comment] 2016-12-06 14:21
Moved wrong issue, damnit.

**Comment by khenderick** [comment] 2016-12-06 14:29
Fixed by #185, packaged in openvstorage-sdm-1.6.8-rev.484.d61c867

**Comment by pploegaert** [comment] 2016-12-07 08:42
Related to: http://tickets.openvstorage.com/browse/OVSSUP-128

**Comment by pploegaert** [comment] 2017-02-24 08:11
Validation continued in:
https://github.com/openvstorage/integrationtests/issues/438

**Comment by pploegaert** [comment] 2017-02-24 10:45
VALIDATION OK:
asdmanger does get restarted

**Closed** 2017-02-24 10:45 UTC
Labels: priority_normal, state_verification, type_bug
