### ISSUE TITLE
Support for  asd-manager removal

### ISSUE THREAD

**Issue by wimpers** [openvstorage/alba-asdmanager#99] opened 2016-08-11 08:54 UTC
Add the option to remove the ASD manager in a clean way from a system and remove any reference in the cluster. This ticket should be able to tackle https://github.com/openvstorage/framework-alba-plugin/issues/180

This should also cover the use case when the node is actually dead.

**Comment by kvanhijf** [comment] 2017-01-20 09:46
ASD manager removal has been implemented by https://github.com/openvstorage/framework/issues/862

**Comment by JeffreyDevloo** [comment] 2017-05-15 12:15
Closing as the related ticket which handled the issue is also closed.

**Closed by JeffreyDevloo** 2017-05-15 12:15 UTC
Labels: priority_normal, state_verification, type_feature
